// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmsbosytllfouwzujros.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtc2Jvc3l0bGxmb3V3enVqcm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzIzODIsImV4cCI6MjA2MjEwODM4Mn0.pUHexa-8A2f3LBfYCRH555qlkEXb0FB3A5JPk-x7uDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);